### PR TITLE
Pretty significant changes for a small app that were inevitably coming

### PR DESCRIPTION
**Pull request by TacoTheDank**
- After endlessly fighting with the project and constantly moving the assets folder around trying to get Gradle to notice it, I decided to just revert back to the old configuration (which isn't a bad thing, just a little weird).
- Updated ```'de.cketti.library.changelog:ckchangelog:1.2.2'``` to ```'de.cketti.library.changelog:ckchangelog-legacy-dialog:2.0.0-SNAPSHOT'``` (contained breaking changes (you'll likely notice what they are, but feel free to ask if you don't))
- ~~Migrated App to AppCompat~~
- ~~Migrated to AndroidX~~
- Bumped version from 2.1 to ~~3.0, as they're pretty significant if you ask me~~ 2.2

### CODE REVIEW

**Comment by TacoTheDank** [comment]
Also you need to upload the new version to the Google Play Store; it's still on 2.08 (from *2016*).

**Comment by TacoTheDank** [comment]
UPDATE: DO NOT MERGE YET. Testing the apks I built, any apks built after migration of app to appcompat crash at startup.

**Comment by uberspot** [comment]
Ok will do, once you fix it I can merge/test/update Play store. I'll do all at the same time :+1: Nice work btw.

**Comment by TacoTheDank** [comment]
Alright. This is the most that can be done. I initially thought the crashing might've been an issue I didn't foresee with calling super on the instance state for the AppCompat library migration, but it's not (as I lint disabled it and it still crashed). App version will just go from 2.1 -> 2.2.

Everything is good to go.

**Comment by TacoTheDank** [comment]
:P

**Pull request merged**
